<<<<<<< HEAD
# Generated by Django 2.1.4 on 2018-12-27 17:42

=======
# Generated by Django 2.1.4 on 2018-12-27 14:56

from django.conf import settings
>>>>>>> 226a8d910ca901ee18372faa6937b127fb93b727
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('text', models.TextField()),
<<<<<<< HEAD
=======
                ('commenter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
>>>>>>> 226a8d910ca901ee18372faa6937b127fb93b727
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('repeating_day', models.IntegerField(default=0)),
                ('active_status', models.BooleanField(default=1)),
                ('holding_date_to', models.DateTimeField()),
                ('holding_date_from', models.DateTimeField()),
                ('ending_date', models.DateTimeField(blank=True)),
                ('creating_date', models.DateTimeField(default=django.utils.timezone.now)),
<<<<<<< HEAD
=======
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
>>>>>>> 226a8d910ca901ee18372faa6937b127fb93b727
            ],
        ),
        migrations.CreateModel(
            name='EventOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yes_count', models.IntegerField(default=0)),
                ('no_count', models.IntegerField(default=0)),
                ('maybe_count', models.IntegerField(default=0)),
                ('has_chosen', models.BooleanField(default=0)),
                ('description', models.TextField()),
                ('from_date', models.DateTimeField()),
                ('to_date', models.DateTimeField()),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Event')),
            ],
        ),
        migrations.CreateModel(
            name='ParticipateIn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Event')),
<<<<<<< HEAD
=======
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
>>>>>>> 226a8d910ca901ee18372faa6937b127fb93b727
            ],
        ),
        migrations.CreateModel(
            name='ReplyComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
<<<<<<< HEAD
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
            ],
        ),
        migrations.AddField(
            model_name='replycomment',
            name='commenter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.User'),
        ),
        migrations.AddField(
            model_name='replycomment',
            name='new_comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='new_comment', to='polls.Comment'),
        ),
        migrations.AddField(
            model_name='replycomment',
            name='replied_comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='old_comment', to='polls.Comment'),
        ),
        migrations.AddField(
            model_name='participatein',
            name='participant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.User'),
        ),
        migrations.AddField(
            model_name='event',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.User'),
        ),
        migrations.AddField(
            model_name='comment',
            name='commenter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.User'),
        ),
=======
                ('commenter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('new_comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='new_comment', to='polls.Comment')),
                ('replied_comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='old_comment', to='polls.Comment')),
            ],
        ),
>>>>>>> 226a8d910ca901ee18372faa6937b127fb93b727
        migrations.AddField(
            model_name='comment',
            name='event_option',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.EventOption'),
        ),
        migrations.AlterUniqueTogether(
            name='replycomment',
            unique_together={('new_comment', 'commenter', 'replied_comment', 'id')},
        ),
        migrations.AlterUniqueTogether(
            name='participatein',
            unique_together={('event', 'participant', 'id')},
        ),
        migrations.AlterUniqueTogether(
            name='eventoption',
            unique_together={('event', 'id')},
        ),
        migrations.AlterUniqueTogether(
            name='comment',
            unique_together={('event_option', 'commenter', 'id')},
        ),
    ]
