# Generated by Django 2.0.7 on 2018-12-24 20:46

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('event_name', models.CharField(max_length=200)),
                ('email_of_creator', models.EmailField(max_length=254)),
                ('description', models.TextField()),
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='EventOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_item_name', models.CharField(max_length=100)),
                ('event_date', models.DateField(verbose_name='day')),
                ('event_date_from_time', models.DateTimeField(verbose_name='From')),
                ('event_date_to_time', models.DateTimeField(verbose_name='To')),
                ('content', models.DateTimeField()),
                ('votes', models.IntegerField(default=0)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Event')),
            ],
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('time_of_authorization', models.DateTimeField(default=datetime.datetime(2018, 12, 24, 20, 46, 47, 499553, tzinfo=utc))),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Event')),
                ('event_items', models.ManyToManyField(to='polls.EventOption')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('time_of_authorization', models.DateTimeField(default=datetime.datetime(2018, 12, 24, 20, 46, 47, 496848, tzinfo=utc))),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Event')),
                ('event_items', models.ManyToManyField(to='polls.EventOption')),
            ],
        ),
    ]
