# Generated by Django 2.0.7 on 2018-12-24 20:53

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='time_of_authorization',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 24, 20, 53, 47, 876201, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='user',
            name='time_of_authorization',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 24, 20, 53, 47, 873610, tzinfo=utc)),
        ),
    ]
