# Generated by Django 2.0.7 on 2018-12-24 20:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20181224_2053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='time_of_authorization',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='user',
            name='time_of_authorization',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
